#!/usr/bin/env python3
"""
GitHub Action runner for ActProof.ai EU AI Act compliance scanner
"""

import os
import sys
import json
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from actproof.scanner import RepositoryScanner
from actproof.compliance.policy_engine import PolicyEngine
from actproof.models.ai_bom import AIBOM


def get_input(name: str, default: str = "") -> str:
    """Get GitHub Action input"""
    return os.environ.get(f"INPUT_{name.upper()}", default)


def set_output(name: str, value: str):
    """Set GitHub Action output"""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"{name}={value}\n")
    else:
        print(f"::set-output name={name}::{value}")


def set_env(name: str, value: str):
    """Set environment variable for subsequent steps"""
    github_env = os.environ.get("GITHUB_ENV")
    if github_env:
        with open(github_env, "a") as f:
            f.write(f"{name}={value}\n")


def create_compliance_issue(compliance_result, critical_gaps, recommendations):
    """Create issue body markdown"""
    report = compliance_result.compliance_report
    score = report["compliance_score"] * 100

    issue_body = f"""# 🔴 EU AI Act Compliance Gaps Detected

**Compliance Score:** {score:.1f}%
**Risk Level:** {compliance_result.risk_level.value}
**Critical Gaps:** {len(critical_gaps)}

## Summary

This repository was scanned by ActProof.ai and found to have compliance gaps according to the EU AI Act.

### Risk Assessment
- **Level:** {compliance_result.risk_level.value}
- **Requires High-Risk Compliance:** {"Yes" if compliance_result.risk_level.value == "HIGH" else "No"}

### Compliance Breakdown
- **Articles Compliant:** {report.get('articles_compliant', 'N/A')}
- **Overall Score:** {score:.1f}%

## Critical Gaps

"""
    for i, gap in enumerate(critical_gaps, 1):
        issue_body += f"{i}. ❌ {gap}\n"

    issue_body += "\n## Recommendations\n\n"
    for i, rec in enumerate(recommendations[:10], 1):  # Limit to top 10
        issue_body += f"{i}. {rec}\n"

    issue_body += f"""
## Component Analysis

- **AI Models Detected:** {report['ai_bom_summary']['models_count']}
- **Datasets Detected:** {report['ai_bom_summary']['datasets_count']}
- **Dependencies:** {report['ai_bom_summary']['dependencies_count']}

## Article 15: Accuracy, Robustness, Cybersecurity

### Accuracy
- **Metrics Defined:** {"✅" if report.get('accuracy', {}).get('metrics_defined') else "❌"}
- **Testing Documented:** {"✅" if report.get('accuracy', {}).get('testing_procedures_documented') else "❌"}
- **Evaluation Performed:** {"✅" if report.get('accuracy', {}).get('model_evaluation_performed') else "❌"}

### Robustness
- **Error Handling:** {"✅" if report.get('robustness', {}).get('error_handling_implemented') else "❌"}
- **Fallback Mechanisms:** {"✅" if report.get('robustness', {}).get('fallback_mechanisms') else "❌"}
- **Input Validation:** {"✅" if report.get('robustness', {}).get('input_validation') else "❌"}

### Cybersecurity
- **Data Encryption:** {"✅" if report.get('cybersecurity', {}).get('data_encryption') else "❌"}
- **Access Controls:** {"✅" if report.get('cybersecurity', {}).get('access_controls') else "❌"}
- **Incident Response Plan:** {"✅" if report.get('cybersecurity', {}).get('incident_response_plan') else "❌"}

---

*Generated by [ActProof.ai](https://github.com/Edoardoba/actproof-action) - EU AI Act Compliance Scanner*
*Commit: {os.environ.get('GITHUB_SHA', 'unknown')[:7]}*
"""

    with open("compliance-issue.md", "w") as f:
        f.write(issue_body)


def main():
    print("🔍 ActProof.ai EU AI Act Compliance Scanner (Local Mode)")
    print("=" * 60)

    # Get inputs
    input_repo_path = get_input("repository_path", ".")
    # Use GITHUB_WORKSPACE if available, otherwise use input path
    workspace = os.environ.get("GITHUB_WORKSPACE", ".")
    if input_repo_path == ".":
        repo_path = Path(workspace)
    else:
        repo_path = Path(workspace) / input_repo_path
    
    output_format = get_input("output_format", "both")
    fail_on_non_compliant = get_input("fail_on_non_compliant", "false").lower() == "true"
    compliance_threshold = float(get_input("compliance_threshold", "80"))
    create_issue = get_input("create_issue", "false").lower() == "true"

    print(f"📂 Repository: {repo_path.absolute()}")
    print(f"🔗 GitHub Repo: {os.environ.get('GITHUB_REPOSITORY', 'local')}")
    print(f"📍 Commit: {os.environ.get('GITHUB_SHA', 'N/A')[:7] if os.environ.get('GITHUB_SHA') else 'N/A'}")
    print(f"📊 Output format: {output_format}")
    print(f"🎯 Compliance threshold: {compliance_threshold}%")
    print()

    # Step 1: Scan repository
    print("Step 1: Scanning repository...")
    scanner = RepositoryScanner(repo_path)
    bom_path = scanner.generate_bom(format="json")
    print(f"✅ AI-BOM generated: {bom_path}")

    # Load AI-BOM
    with open(bom_path, 'r') as f:
        bom_data = json.load(f)
    ai_bom = AIBOM.model_validate(bom_data)

    print(f"   - Models detected: {len(ai_bom.models)}")
    print(f"   - Datasets detected: {len(ai_bom.datasets)}")
    print(f"   - Dependencies: {len(ai_bom.dependencies)}")
    print()

    # Step 2: Evaluate compliance
    print("Step 2: Evaluating EU AI Act compliance...")
    engine = PolicyEngine(repo_path)
    result = engine.evaluate_compliance(ai_bom)

    compliance_score = result.compliance_report["compliance_score"] * 100
    print(f"✅ Compliance evaluation complete")
    print(f"   - Compliance score: {compliance_score:.1f}%")
    print(f"   - Risk level: {result.risk_level.value}")
    print(f"   - Critical gaps: {len(result.requirements_check.critical_gaps)}")
    print()

    # Step 3: Generate reports
    print("Step 3: Generating compliance reports...")

    # JSON report
    if output_format in ["json", "both"]:
        json_report = {
            "scan_timestamp": ai_bom.scan_timestamp.isoformat(),
            "repository": os.environ.get("GITHUB_REPOSITORY", "unknown"),
            "commit": os.environ.get("GITHUB_SHA", "unknown"),
            "compliance_score": compliance_score,
            "compliant": result.compliant,
            "risk_level": result.risk_level.value,
            "critical_gaps": result.requirements_check.critical_gaps,
            "recommendations": result.requirements_check.recommendations,
            "compliance_report": result.compliance_report,
        }

        with open("actproof-report.json", "w") as f:
            json.dump(json_report, f, indent=2, default=str)
        print(f"✅ JSON report: actproof-report.json")

    # HTML report (simplified)
    if output_format in ["html", "both"]:
        html_report = f"""<!DOCTYPE html>
<html>
<head>
    <title>ActProof.ai Compliance Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 1200px; margin: 40px auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; }}
        .score {{ font-size: 48px; font-weight: bold; }}
        .score.pass {{ color: #10b981; }}
        .score.fail {{ color: #ef4444; }}
        .section {{ background: #f9fafb; padding: 20px; margin: 20px 0; border-radius: 8px; }}
        .gap {{ background: #fee2e2; padding: 10px; margin: 5px 0; border-left: 4px solid #ef4444; }}
        .recommendation {{ background: #dbeafe; padding: 10px; margin: 5px 0; border-left: 4px solid #3b82f6; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ ActProof.ai EU AI Act Compliance Report</h1>
        <p>Repository: {os.environ.get('GITHUB_REPOSITORY', 'unknown')}</p>
        <p>Commit: {os.environ.get('GITHUB_SHA', 'unknown')[:7]}</p>
    </div>

    <div class="section">
        <h2>Compliance Score</h2>
        <div class="score {'pass' if result.compliant else 'fail'}">{compliance_score:.1f}%</div>
        <p><strong>Status:</strong> {'✅ COMPLIANT' if result.compliant else '❌ NON-COMPLIANT'}</p>
        <p><strong>Risk Level:</strong> {result.risk_level.value}</p>
    </div>

    <div class="section">
        <h2>Critical Gaps ({len(result.requirements_check.critical_gaps)})</h2>
        {"".join(f'<div class="gap">❌ {gap}</div>' for gap in result.requirements_check.critical_gaps)}
    </div>

    <div class="section">
        <h2>Recommendations ({len(result.requirements_check.recommendations)})</h2>
        {"".join(f'<div class="recommendation">💡 {rec}</div>' for rec in result.requirements_check.recommendations[:10])}
    </div>

    <div class="section">
        <h2>Article 15: Accuracy, Robustness, Cybersecurity</h2>
        <h3>Accuracy</h3>
        <p>Metrics Defined: {'✅' if result.compliance_report.get('accuracy', {}).get('metrics_defined') else '❌'}</p>
        <p>Testing Documented: {'✅' if result.compliance_report.get('accuracy', {}).get('testing_procedures_documented') else '❌'}</p>

        <h3>Robustness</h3>
        <p>Error Handling: {'✅' if result.compliance_report.get('robustness', {}).get('error_handling_implemented') else '❌'}</p>
        <p>Fallback Mechanisms: {'✅' if result.compliance_report.get('robustness', {}).get('fallback_mechanisms') else '❌'}</p>

        <h3>Cybersecurity</h3>
        <p>Data Encryption: {'✅' if result.compliance_report.get('cybersecurity', {}).get('data_encryption') else '❌'}</p>
        <p>Access Controls: {'✅' if result.compliance_report.get('cybersecurity', {}).get('access_controls') else '❌'}</p>
    </div>
</body>
</html>"""

        with open("actproof-report.html", "w") as f:
            f.write(html_report)
        print(f"✅ HTML report: actproof-report.html")

    print()

    # Step 4: Set outputs
    print("Step 4: Setting GitHub Action outputs...")
    set_output("compliance_score", str(compliance_score))
    set_output("compliant", str(result.compliant).lower())
    set_output("risk_level", result.risk_level.value)
    set_output("critical_gaps_count", str(len(result.requirements_check.critical_gaps)))
    set_output("report_path", "actproof-report.json")
    set_output("ai_bom_path", str(bom_path))

    # Step 5: Create issue if requested
    if create_issue and not result.compliant:
        print("Step 5: Creating compliance issue...")
        create_compliance_issue(
            result,
            result.requirements_check.critical_gaps,
            result.requirements_check.recommendations
        )
        set_env("COMPLIANCE_FAILED", "true")
        print("✅ Issue body created: compliance-issue.md")
    else:
        set_env("COMPLIANCE_FAILED", "false")

    print()

    # Step 6: Determine if workflow should fail
    if fail_on_non_compliant and compliance_score < compliance_threshold:
        print(f"❌ FAILURE: Compliance score {compliance_score:.1f}% is below threshold {compliance_threshold}%")
        sys.exit(1)
    else:
        print(f"✅ SUCCESS: Compliance evaluation complete")
        if result.compliant:
            print(f"   🎉 Repository is EU AI Act compliant!")
        else:
            print(f"   ⚠️  Repository has {len(result.requirements_check.critical_gaps)} critical gaps")


if __name__ == "__main__":
    main()

