#!/usr/bin/env python3
"""
GitHub Action runner for ActProof.ai - Calls hosted API
Triggers compliance scan via https://app.actproof.ai/ API
"""

import os
import sys
import json
import requests
from pathlib import Path


def get_input(name: str, default: str = "") -> str:
    """Get GitHub Action input"""
    return os.environ.get(f"INPUT_{name.upper()}", default)


def set_output(name: str, value: str):
    """Set GitHub Action output"""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"{name}={value}\n")
    else:
        print(f"::set-output name={name}::{value}")


def set_env(name: str, value: str):
    """Set environment variable for subsequent steps"""
    github_env = os.environ.get("GITHUB_ENV")
    if github_env:
        with open(github_env, "a") as f:
            f.write(f"{name}={value}\n")


def create_compliance_issue(result_data, critical_gaps, recommendations):
    """Create issue body markdown"""
    score = result_data.get("compliance_score", 0)
    risk_level = result_data.get("risk_level", "UNKNOWN")

    issue_body = f"""# 🔴 EU AI Act Compliance Gaps Detected

**Compliance Score:** {score:.1f}%
**Risk Level:** {risk_level}
**Critical Gaps:** {len(critical_gaps)}

## Summary

This repository was scanned by [ActProof.ai](https://app.actproof.ai/) and found to have compliance gaps according to the EU AI Act.

### Risk Assessment
- **Level:** {risk_level}
- **Requires High-Risk Compliance:** {"Yes" if risk_level == "HIGH" else "No"}

### Compliance Breakdown
- **Overall Score:** {score:.1f}%

## Critical Gaps

"""
    for i, gap in enumerate(critical_gaps, 1):
        issue_body += f"{i}. ❌ {gap}\n"

    issue_body += "\n## Recommendations\n\n"
    for i, rec in enumerate(recommendations[:10], 1):
        issue_body += f"{i}. {rec}\n"

    report = result_data.get("compliance_report", {})
    issue_body += f"""
## Article 15: Accuracy, Robustness, Cybersecurity

### Accuracy
- **Metrics Defined:** {"✅" if report.get('accuracy', {}).get('metrics_defined') else "❌"}
- **Testing Documented:** {"✅" if report.get('accuracy', {}).get('testing_procedures_documented') else "❌"}
- **Evaluation Performed:** {"✅" if report.get('accuracy', {}).get('model_evaluation_performed') else "❌"}

### Robustness
- **Error Handling:** {"✅" if report.get('robustness', {}).get('error_handling_implemented') else "❌"}
- **Fallback Mechanisms:** {"✅" if report.get('robustness', {}).get('fallback_mechanisms') else "❌"}
- **Input Validation:** {"✅" if report.get('robustness', {}).get('input_validation') else "❌"}

### Cybersecurity
- **Data Encryption:** {"✅" if report.get('cybersecurity', {}).get('data_encryption') else "❌"}
- **Access Controls:** {"✅" if report.get('cybersecurity', {}).get('access_controls') else "❌"}
- **Incident Response Plan:** {"✅" if report.get('cybersecurity', {}).get('incident_response_plan') else "❌"}

---

*Generated by [ActProof.ai](https://app.actproof.ai) - EU AI Act Compliance Scanner*
*Commit: {os.environ.get('GITHUB_SHA', 'unknown')[:7]}*
*View full report: https://app.actproof.ai/dashboard*
"""

    with open("compliance-issue.md", "w") as f:
        f.write(issue_body)


def main():
    print("🔍 ActProof.ai EU AI Act Compliance Scanner")
    print("=" * 60)

    # Get inputs
    api_url = get_input("api_url", "https://app.actproof.ai")
    api_key = get_input("api_key", "")  # Optional - defaults to public marketplace token
    fail_on_non_compliant = get_input("fail_on_non_compliant", "false").lower() == "true"
    compliance_threshold = float(get_input("compliance_threshold", "80"))
    create_issue = get_input("create_issue", "false").lower() == "true"

    # Default token for GitHub Marketplace (automatically used if no api_key provided)
    DEFAULT_MARKETPLACE_TOKEN = "bab9ba47fd28e4abb985acbd2b23a6c64d0c3640621d85715af54ce67ed306c3"
    
    # Use provided token or default marketplace token
    token_to_use = api_key if api_key else DEFAULT_MARKETPLACE_TOKEN
    if not api_key:
        print("ℹ️  Using default ActProof.ai token (works out of the box!)")
        print("   To use your own token, set the api_key input")
        print()

    # GitHub context
    github_repository = os.environ.get("GITHUB_REPOSITORY", "")
    github_sha = os.environ.get("GITHUB_SHA", "")
    github_ref = os.environ.get("GITHUB_REF", "")
    github_server_url = os.environ.get("GITHUB_SERVER_URL", "https://github.com")

    # Construct repository URL
    repo_url = f"{github_server_url}/{github_repository}"

    print(f"📂 Repository: {github_repository}")
    print(f"🔗 URL: {repo_url}")
    print(f"📍 Commit: {github_sha[:7]}")
    print(f"🌐 API: {api_url}")
    print()

    # Step 1: Trigger scan via API
    print("Step 1: Triggering compliance scan via API...")
    
    headers = {
        "Authorization": f"Bearer {token_to_use}",
        "Content-Type": "application/json"
    }
    
    # Prepare JSON payload (the API will clone the repository)
    payload = {
        "repository_url": repo_url,
        "commit_sha": github_sha,
        "branch": github_ref.replace("refs/heads/", "").replace("refs/tags/", ""),
        "source": "github-action",
        "metadata": {
            "workflow": os.environ.get("GITHUB_WORKFLOW", ""),
            "run_id": os.environ.get("GITHUB_RUN_ID", ""),
            "actor": os.environ.get("GITHUB_ACTOR", ""),
        }
    }
    
    print(f"   Sending scan request to {api_url}/api/scan")
    print(f"   Repository URL: {repo_url}")
    print()

    try:
        # Call scan endpoint (JSON payload - API clones the repo)
        response = requests.post(
            f"{api_url}/api/scan",
            json=payload,
            headers=headers,
            timeout=300  # 5 minutes timeout for cloning + scanning
        )
        response.raise_for_status()
        scan_result = response.json()

        # Extract results from API response
        scan_id = scan_result.get("scan_id")
        status = scan_result.get("status", "unknown")
        
        print(f"✅ Scan triggered successfully")
        print(f"   - Scan ID: {scan_id}")
        print(f"   - Status: {status}")
        print()

        # Step 2: Extract compliance data from response
        print("Step 2: Processing compliance results...")

        # The API returns nested compliance_result
        compliance_result = scan_result.get("compliance_result", {})
        compliance_report = compliance_result.get("compliance_report", {})
        requirements_check = compliance_result.get("requirements_check", {})
        
        # Extract key metrics
        compliance_score = compliance_report.get("compliance_score", 0) * 100  # Convert to percentage
        compliant = compliance_result.get("compliant", False)
        risk_level = compliance_result.get("risk_level", "UNKNOWN")
        critical_gaps = requirements_check.get("critical_gaps", [])
        recommendations = requirements_check.get("recommendations", [])
        
        print(f"   - Compliance Score: {compliance_score:.1f}%")
        print(f"   - Status: {'✅ COMPLIANT' if compliant else '❌ NON-COMPLIANT'}")
        print(f"   - Risk Level: {risk_level}")
        print(f"   - Critical Gaps: {len(critical_gaps)}")

        print(f"✅ Results processed")
        print(f"   - Compliance score: {compliance_score:.1f}%")
        print(f"   - Risk level: {risk_level}")
        print(f"   - Critical gaps: {len(critical_gaps)}")
        print()

        # Step 4: Generate reports
        print("Step 4: Generating compliance reports...")

        # JSON report
        json_report = {
            "scan_id": scan_id,
            "scan_timestamp": scan_result.get("scan_timestamp"),
            "repository": github_repository,
            "commit": github_sha,
            "compliance_score": compliance_score,
            "compliant": compliant,
            "risk_level": risk_level,
            "critical_gaps": critical_gaps,
            "recommendations": recommendations,
            "compliance_report": compliance_result if compliance_result else {},
            "dashboard_url": f"{api_url}/dashboard?scan_id={scan_id}"
        }

        with open("actproof-report.json", "w") as f:
            json.dump(json_report, f, indent=2, default=str)
        print(f"✅ JSON report: actproof-report.json")

        # HTML report with link to dashboard
        html_report = f"""<!DOCTYPE html>
<html>
<head>
    <title>ActProof.ai Compliance Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 1200px; margin: 40px auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; }}
        .score {{ font-size: 48px; font-weight: bold; }}
        .score.pass {{ color: #10b981; }}
        .score.fail {{ color: #ef4444; }}
        .section {{ background: #f9fafb; padding: 20px; margin: 20px 0; border-radius: 8px; }}
        .gap {{ background: #fee2e2; padding: 10px; margin: 5px 0; border-left: 4px solid #ef4444; }}
        .recommendation {{ background: #dbeafe; padding: 10px; margin: 5px 0; border-left: 4px solid #3b82f6; }}
        .dashboard-link {{ background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 20px 0; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ ActProof.ai EU AI Act Compliance Report</h1>
        <p>Repository: {github_repository}</p>
        <p>Commit: {github_sha[:7]}</p>
        <a href="{api_url}/dashboard?scan_id={scan_id}" class="dashboard-link">View Full Dashboard →</a>
    </div>

    <div class="section">
        <h2>Compliance Score</h2>
        <div class="score {'pass' if compliant else 'fail'}">{compliance_score:.1f}%</div>
        <p><strong>Status:</strong> {'✅ COMPLIANT' if compliant else '❌ NON-COMPLIANT'}</p>
        <p><strong>Risk Level:</strong> {risk_level}</p>
    </div>

    <div class="section">
        <h2>Critical Gaps ({len(critical_gaps)})</h2>
        {"".join(f'<div class="gap">❌ {gap}</div>' for gap in critical_gaps) if critical_gaps else '<p>No critical gaps found!</p>'}
    </div>

    <div class="section">
        <h2>Recommendations ({len(recommendations)})</h2>
        {"".join(f'<div class="recommendation">💡 {rec}</div>' for rec in recommendations[:10]) if recommendations else '<p>No recommendations at this time.</p>'}
    </div>

    <div class="section">
        <a href="{api_url}/dashboard?scan_id={scan_id}" class="dashboard-link">View Full Interactive Dashboard →</a>
    </div>
</body>
</html>"""

        with open("actproof-report.html", "w") as f:
            f.write(html_report)
        print(f"✅ HTML report: actproof-report.html")
        print()

        # Step 5: Set outputs
        print("Step 5: Setting GitHub Action outputs...")
        set_output("compliance_score", str(compliance_score))
        set_output("compliant", str(compliant).lower())
        set_output("risk_level", risk_level)
        set_output("critical_gaps_count", str(len(critical_gaps)))
        set_output("report_path", "actproof-report.json")
        set_output("scan_id", scan_id)
        set_output("dashboard_url", f"{api_url}/dashboard?scan_id={scan_id}")

        # Step 6: Create issue if requested
        if create_issue and not compliant:
            print("Step 6: Creating compliance issue...")
            create_compliance_issue(
                json_report,
                critical_gaps,
                recommendations
            )
            set_env("COMPLIANCE_FAILED", "true")
            print("✅ Issue body created: compliance-issue.md")
        else:
            set_env("COMPLIANCE_FAILED", "false")

        print()

        # Step 7: Determine if workflow should fail
        if fail_on_non_compliant and compliance_score < compliance_threshold:
            print(f"❌ FAILURE: Compliance score {compliance_score:.1f}% is below threshold {compliance_threshold}%")
            print(f"   View details: {api_url}/dashboard?scan_id={scan_id}")
            sys.exit(1)
        else:
            print(f"✅ SUCCESS: Compliance evaluation complete")
            print(f"   View details: {api_url}/dashboard?scan_id={scan_id}")
            if compliant:
                print(f"   🎉 Repository is EU AI Act compliant!")
            else:
                print(f"   ⚠️  Repository has {len(critical_gaps)} critical gaps")

    except requests.exceptions.SSLError as e:
        print(f"❌ SSL Error: Cannot connect to {api_url}")
        print(f"   Error: {str(e)}")
        print(f"   This usually means:")
        print(f"   1. The server is not deployed or not accessible")
        print(f"   2. SSL certificate is invalid or self-signed")
        print(f"   3. The API URL is incorrect")
        print(f"   Please verify that {api_url} is accessible and has a valid SSL certificate")
        sys.exit(1)
    except requests.exceptions.ConnectionError as e:
        print(f"❌ Connection Error: Cannot reach {api_url}")
        print(f"   Error: {str(e)}")
        print(f"   Please verify that:")
        print(f"   1. The server is running and accessible")
        print(f"   2. The API URL is correct: {api_url}")
        print(f"   3. There are no firewall/network restrictions")
        sys.exit(1)
    except requests.exceptions.RequestException as e:
        print(f"❌ API Error: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"   Status: {e.response.status_code}")
            print(f"   Response: {e.response.text}")
        else:
            print(f"   Full error: {str(e)}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()

